world_string = """
  G  L2S . . . . . . . . . .  . 
  .   .  . . . . . . . . . .  .   
  .   .  . . . . . . . . . .  .   
  @   @  . . . . . . . . . .  .   
 L0E  .  . . . . . @ @ @ @ @  @   
  .   .  . . . . . . . . . .  .   
  .   .  . . . . . . . . . . L1W
  .   .  . . . . . @ . G . .  .   
  .   .  . . . . . @ @ @ @ @  @   
  .   .  . . . . . . . . . .  .   
  .   .  . . G . . . . . X X  .   
  .   .  . . . . . . . . X X  G"""


[[agents]]
start_positions = [{ i_max = 3, j_min = 2 }, { i_min = 4, i_max = 5 }]

[[agents]]
start_positions = [{ i_max = 3, j_min = 2 }]

[[agents]]
start_positions = [
  { i_max = 3, j_min = 2 },
  { i_min = 1, i_max = 2, j_max = 1 },
]

[[agents]]
start_positions = [{ i_max = 3, j_min = 2 }]
