# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector:
  type: "epsilon_greedy"
  epsilon_start: 1.0
  epsilon_finish: 0.05
  epsilon_anneal_time: 50000

macro_action_selector:
  type: "epsilon_greedy"
  epsilon_start: 1.0
  epsilon_finish: 0.05
  epsilon_anneal_time: 50000

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "q_learner"
double_q: True
mixer: "vdn"
name: "vdn-cnn-no-ir"

mean_weight: True
intrinsic_switch: 0
reward_switch: 1

agent: "cnn"