env: lle

env_args:
  map: 6
  seed: 0
  obs_type: layered

test_greedy: True
test_nepisode: 1
test_interval: 5000
log_interval: 5000
runner_log_interval: 5000
learner_log_interval: 5000
t_max: 4000000
obs_agent_id: True
obs_last_action: True
runner: "episode"
