env: lle

env_args:
  level: 6
  seed: 0
  obs_type: layered

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2050000
obs_agent_id: True
obs_last_action: True
runner: "episode"
